### ISSUE TITLE
MVP for Manager Instant App - October 2023 release

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#277]
I thought it might be helpful to outline in an issue the details of what we intend to be the minimum viable product (MVP) for the first release of the Manager template. This issue would help communicate to keep us all on the same page and to prioritize the issues we log into this repo.

Here's what we know so far (I used [this issue](https://devtopia.esri.com/WebGIS/solutions-web-development/issues/44) as a reference), and this list can evolve as we work through the development:

_** if needs further discussions_

### Table
- [x] View data in a table
- [x] Switch between feature/table layers
- [x] Update a feature/record using the Editor widget
- [x] Add attachments
- [x] Select records in the table to view information
- [x] Delete selected record.
- [x] Download selected records in CSV format
- [x] View count of records in table](https://github.com/Esri/solutions-components/issues/270)

### Map
- [x] View features on the map
- [x] Switch between web maps
- [x] Zoom on the map to selected features in the table
- [x] Select a feature on the map to view information (should also select in table) **
- [x] Map tools: zoom, home, search, basemap switcher, legend, fullscreen

### Other support
- [ ] Filter feature and records in the app (through editing json file, at runtime)
- [x] Add and edit related records using the Editor widget **
- [x] Selection management options: select all, show selected, clear selection, switch selected
- [x] Auto-refresh when changes are made (honor map viewer refresh) **
- [x] Manually refresh records **

### Out of scope for MVP
- [ ] Set visibility and order of the fields in configuration
- [ ] Edit multiple records and features (batch)](https://github.com/Esri/solutions-components/issues/272) **
- [ ] Support for web scenes **
- [ ] [Support for mobile devices](https://github.com/Esri/solutions-components/issues/274)
- [ ] Create a new record using the Editor widget](https://github.com/Esri/solutions-components/issues/275)
- [ ] Create a new feature using the Editor widget **
- [ ] Switch between app Layouts at runtime
- [ ] Configuration to show/hide the map in the app layout](https://github.com/Esri/solutions-components/issues/273) **
- [ ] Options: Horizontal, Vertical *
- [ ] Support floor filtering](https://github.com/Esri/solutions-components/issues/130) **

**Comment by azizaparveen** [comment]
This is completed.
