### ISSUE TITLE
What's coming for Manager in February 2024 (2024.R01)

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#411]
**New functionalities** 

- [ ] Out of beta
- [ ] Show a list of selected records for navigation  (https://github.com/Esri/solutions-components/issues/417)
- [ ] Filter feature and records in the app (configuration and runtime, https://github.com/Esri/solutions-components/issues/280)
- [ ] Set visibility and order of the fields in configuration
- [ ] Create a new record using the Editor widget](https://github.com/Esri/solutions-components/issues/275) (need design discussion)
- [ ] Create a new feature using the Editor widget **(need design discussion)
- [ ] Support floor filtering](https://github.com/Esri/solutions-components/issues/130) **
- [ ] Add support for url parameter (https://github.com/Esri/solutions-components/issues/330)
- [ ] Add support to change field visibility at runtime (https://github.com/Esri/solutions-components/issues/350)
- [ ] Provide config option to define sort field and order (https://github.com/Esri/solutions-components/issues/308)
- [ ] Evaluate mobile UI/UX for Manager (https://github.com/Esri/solutions-components/issues/274)

**Out of scope for February release:**
- [ ]  Edit multiple records and features (batch)](https://github.com/Esri/solutions-components/issues/272) **
- [ ] Configuration to show/hide the map in the app layout](https://github.com/Esri/solutions-components/issues/273) **
Options: Horizontal, Vertical *
- [ ]  Support for web scenes **
